### ISSUE TITLE
ATmega329P and segment LCD

### ISSUE THREAD

**Issue by furieuxjk** [MCUdude/ButterflyCore#2]
Hello!

First of all - thanks for this great Arduino Core!

I have LCD which is 1/3 bias and 1/4 duty. It has only two digits (8 pins in total, 4 common pins and 4 segment pins).
I would like to try to use this LCD with ATmega329P. So I connected all four common pins to ATmega329P COM0...COM3 and also segment pins to SEG0...SEG3.

Now, questions:
1) where and how I can define which segments belong to which pins?
2) I have 16 MHz external crystal connected to ATmega329P - will it work with LCD? Everywhere is mentioned 32,768 kHz crystal, but not 16 MHz.

**Comment by MCUdude** [comment]
Hi!
I haven't worked with the ATmega LCD microcontrollers for a long time, and this core is just some work I did a few years ago. I haven't tested it on ATmega329P, but I guess it will work.

1. I'm not quite sure. You should check out the [butterfly example code](https://github.com/MCUdude/ButterflyCore/tree/master/avr/libraries/Butterfly) to see how the "default" butterfly LCD is controlled.
2. The 32.768kHz crystal is only for the real time clock. The microcontroller needs a much higher clock, typically 8 or 16 MHz.

**Comment by furieuxjk** [comment]
Ok, will try to investigate further.
